// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";

function make(children) {
  return ReasonReact.wrapJsForReason(React.Fragment, (function () {
                return { };
              }), children);
}

export {
  make ,
  
}
/* react Not a pure module */
